# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is ????? ../bin/eventfilter

HEADERS += digitdialog.h \
           button.h 
SOURCES += main.cpp \
           digitdialog.cpp \
           button.cpp 
TARGET=../bin/eventfilter
